FROM openjdk:11               # FROM<image>
VOLUME /tmp                   # Temporary location to run
EXPOSE 8080                   # Provide port number
ADD ../backend/build/lib/backend-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java","-jar","/backend-0.0.1-SNAPSHOT.jar"]
